from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import random
import sys
import time
from typing import Dict, List

import torch

from trianglefit.direct.config import LossWeights
from trianglefit.direct.fit_core import _background_grid_to_json, _decoded_to_cpu, _render_export_image
from trianglefit.direct.io import load_image, save_image
from trianglefit.direct.losses import CompositeEllipseLoss
from trianglefit.direct.renderer import render_parameters
from trianglefit.direct.utils import ensure_dir, flatten_metrics, serialize_json, seed_all

from .config import UNetTriangleConfig
from .model import TriangleUNetGenerator


@dataclass(frozen=True)
class UNetFitArtifacts:
    final_image_path: str
    ellipses_path: str
    metrics_path: str
    progress_dir: str


def parse_args(argv: List[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit a single image with a U-Net generated triangle set.")
    parser.add_argument("--input", required=True, help="Path to the target image.")
    parser.add_argument("--output", required=True, help="Directory to store final.png, ellipses.json and metrics.json.")
    parser.add_argument("--num-triangles", type=int, default=300, help="Number of triangles generated by U-Net.")
    parser.add_argument("--steps", type=int, default=3000, help="Number of optimization steps.")
    parser.add_argument("--work-size", type=int, default=256, help="Longest side used during optimization.")
    parser.add_argument("--seed", type=int, default=None, help="Optional global random seed.")
    parser.add_argument("--device", default="auto", help="Torch device, for example auto, cpu or cuda.")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate for U-Net weights.")
    parser.add_argument("--fast", action="store_true", help="Use L1 only and skip LPIPS.")
    return parser.parse_args(argv)


def resolve_seed(seed: int | None) -> int:
    if seed is not None:
        return int(seed)
    return random.SystemRandom().randrange(0, 2**31)


def resolve_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(device_arg)


def _export_triangles_json(
    decoded,
    output_path: Path,
    image_width: int,
    image_height: int,
    config: UNetTriangleConfig,
    perceptual_mode: str,
) -> None:
    cpu_decoded = _decoded_to_cpu(decoded)
    payload = {
        "image_width": image_width,
        "image_height": image_height,
        "num_triangles": config.num_triangles,
        "base_ellipse_count": config.base_count(),
        "texture_ellipse_count": config.texture_count(),
        "accent_ellipse_count": config.accent_count(),
        "background_grid_height": int(cpu_decoded.background_grid_rgb.shape[-2]) if cpu_decoded.background_grid_rgb is not None else 0,
        "background_grid_width": int(cpu_decoded.background_grid_rgb.shape[-1]) if cpu_decoded.background_grid_rgb is not None else 0,
        "background_grid_rgb": _background_grid_to_json(cpu_decoded),
        "final_temperature": config.mask_temperature,
        "export_render_mode": "hard_edges",
        "perceptual_mode": perceptual_mode,
        "ellipses": cpu_decoded.to_json_list(),
    }
    serialize_json(payload, output_path)


def fit_image_file(input_path: Path, output_dir: Path, config: UNetTriangleConfig, device: torch.device) -> UNetFitArtifacts:
    seed_all(config.seed)
    ensure_dir(output_dir)
    progress_dir = ensure_dir(output_dir / "progress")

    loaded = load_image(input_path, config.work_size)
    target_work = loaded.working.to(device=device, dtype=torch.float32)
    _, _, work_height, work_width = target_work.shape
    full_height = loaded.original.shape[-2]
    full_width = loaded.original.shape[-1]
    save_image(loaded.working, output_dir / "target_work.png")

    generator = TriangleUNetGenerator(
        num_triangles=config.num_triangles,
        base_count=config.base_count(),
        texture_count=config.texture_count(),
        hidden_channels=config.hidden_channels,
        min_size=config.min_size,
        base_max_size=config.base_max_size,
        texture_max_size=config.texture_max_size,
    ).to(device=device)
    optimizer = torch.optim.AdamW(generator.parameters(), lr=config.lr)

    loss_weights = LossWeights(l1=config.l1_weight, lpips=config.lpips_weight)
    loss_module = CompositeEllipseLoss(
        area_regularization_weight=0.0,
        perceptual_enabled=config.lpips_weight > 0.0,
        edge_loss_enabled=False,
        band_loss_enabled=False,
    ).to(device=device)
    loss_module.set_target(target_work)

    base_count, texture_count, accent_count = generator.role_counts()
    history: List[Dict[str, object]] = []
    best_loss = float("inf")
    best_decoded = None
    start_time = time.perf_counter()
    print(
        "Starting U-Net fit: triangles=%d steps=%d work_size=%dx%d device=%s perceptual=%s"
        % (config.num_triangles, config.steps, work_width, work_height, device, loss_module.perceptual_mode),
        flush=True,
    )

    for step in range(config.steps):
        one_based_step = step + 1
        decoded = generator(target_work)
        render = render_parameters(
            decoded=decoded,
            height=work_height,
            width=work_width,
            mask_temperature=config.mask_temperature,
            background_rgb=(1.0, 1.0, 1.0),
            hard_edges=False,
            active_base_count=base_count,
            active_texture_count=texture_count,
            active_accent_count=accent_count,
        )
        loss, metrics, _ = loss_module(
            render.image,
            target_work,
            render.decoded,
            loss_weights=loss_weights,
            weighted_l1_edge_gain=0.0,
            enable_lpips=config.lpips_weight > 0.0,
        )
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(generator.parameters(), max_norm=1.0)
        optimizer.step()

        current_loss = float(loss.detach().cpu().item())
        if current_loss < best_loss:
            best_loss = current_loss
            best_decoded = _decoded_to_cpu(render.decoded)

        if one_based_step == 1 or one_based_step % config.metrics_every == 0 or one_based_step == config.steps:
            entry: Dict[str, object] = {
                "step": one_based_step,
                "active_base_ellipses": base_count,
                "active_texture_ellipses": texture_count,
                "active_accent_ellipses": accent_count,
                "mask_temperature": config.mask_temperature,
            }
            entry.update(flatten_metrics(metrics))
            history.append(entry)
            elapsed = time.perf_counter() - start_time
            eta = (elapsed / float(one_based_step)) * max(0, config.steps - one_based_step)
            print(
                "[step %d/%d] loss=%.6f l1=%.6f lpips=%.6f rmse=%.6f elapsed=%.1fs eta=%.1fs"
                % (one_based_step, config.steps, entry["loss"], entry["l1"], entry["lpips"], entry["rgb_rmse"], elapsed, eta),
                flush=True,
            )

        if one_based_step % config.progress_every == 0 or one_based_step == config.steps:
            progress_render = _render_export_image(
                decoded=render.decoded,
                height=work_height,
                width=work_width,
                background_rgb=(1.0, 1.0, 1.0),
                active_base_count=base_count,
                active_texture_count=texture_count,
                active_accent_count=accent_count,
            )
            save_image(progress_render, progress_dir / ("step_%04d.png" % one_based_step))

    final_decoded = generator(target_work)
    final_render = _render_export_image(
        decoded=final_decoded,
        height=work_height,
        width=work_width,
        background_rgb=(1.0, 1.0, 1.0),
        active_base_count=base_count,
        active_texture_count=texture_count,
        active_accent_count=accent_count,
    )
    save_image(final_render, output_dir / "final.png")
    save_image(final_render, output_dir / "final_work.png")
    final_fullres = _render_export_image(
        decoded=final_decoded,
        height=full_height,
        width=full_width,
        background_rgb=(1.0, 1.0, 1.0),
        active_base_count=base_count,
        active_texture_count=texture_count,
        active_accent_count=accent_count,
    )
    save_image(final_fullres, output_dir / "final_fullres.png")

    if best_decoded is not None:
        best_render = _render_export_image(
            decoded=best_decoded,
            height=work_height,
            width=work_width,
            background_rgb=(1.0, 1.0, 1.0),
            active_base_count=base_count,
            active_texture_count=texture_count,
            active_accent_count=accent_count,
        )
        save_image(best_render, output_dir / "best.png")

    _export_triangles_json(
        decoded=final_decoded,
        output_path=output_dir / "ellipses.json",
        image_width=full_width,
        image_height=full_height,
        config=config,
        perceptual_mode=loss_module.perceptual_mode,
    )
    serialize_json(
        {
            "config": config.to_dict(),
            "source_image": loaded.path,
            "image_size": {"width": full_width, "height": full_height},
            "working_size": {"width": work_width, "height": work_height},
            "perceptual_mode": loss_module.perceptual_mode,
            "history": history,
            "final": history[-1] if history else {},
            "best_loss": best_loss,
        },
        output_dir / "metrics.json",
    )
    print("Completed U-Net fit in %.1fs" % (time.perf_counter() - start_time), flush=True)

    return UNetFitArtifacts(
        final_image_path=str(output_dir / "final.png"),
        ellipses_path=str(output_dir / "ellipses.json"),
        metrics_path=str(output_dir / "metrics.json"),
        progress_dir=str(progress_dir),
    )


def main(argv: List[str] | None = None) -> int:
    args = parse_args(argv)
    seed = resolve_seed(args.seed)
    device = resolve_device(args.device)
    config = UNetTriangleConfig(
        num_triangles=args.num_triangles,
        work_size=args.work_size,
        steps=args.steps,
        seed=seed,
        lr=args.lr,
        lpips_weight=0.0 if args.fast else 0.3,
    )
    print("Using seed=%d device=%s" % (seed, device))
    artifacts = fit_image_file(input_path=Path(args.input), output_dir=Path(args.output), config=config, device=device)
    print("Saved final image to %s" % artifacts.final_image_path)
    print("Saved triangle parameters to %s" % artifacts.ellipses_path)
    print("Saved metrics to %s" % artifacts.metrics_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))



